---
title: "Disclaimer"
---
### TERMS OF USE 

The INDIVIDUALIZED FRAMINGHAM LUNG FUNCTION DECLINE PREDICTOR (the “LUNG FUNCTION PREDICTOR”) is a web-based tool to provide a predictive model of lung function decline over time.  The LUNG FUNCTION PREDICTOR was developed by Dr. Mohsen Sadatsafavi, Amin Adibi, Dr. Wenjia Chen, Dr. Abdollah Safari, Jane Krot, Dr. Mark Fitzgerald and Dr. Don Sin at UBC. 
You (the "End User") is granted access to use the LUNG FUNCTION PREDICTOR only on the condition that the End User agrees to the terms of use set forth below.  

The End User acknowledges that the LUNG FUNCTION PREDICTOR developed and conceived by UBC, including any and all improvements, variations, updates, upgrades, modifications, enhancements or derivative works (the “LUNG FUNCTION PREDICTOR”) is owned by UBC and that UBC specifically retains the right to grant licenses of the LUNG FUNCTION PREDICTOR to other persons.   
The LUNG FUNCTION PREDICTOR is provided to the End User for research, educational and non-commercial purposes only. 

CLINICAL USE ADVISORY - 
THE LUNG FUNCTION PREDICTOR IS AN EXPERIMENTAL TECHNOLOGY AND HAS NOT BEEN TESTED OR APPROVED FOR USE IN CONNECTION WITH ANY HUMAN CLINICAL USE.  THE LUNG FUNCTION PREDICTOR AND ANY CONTENT OR OTHER INFORMATION CONTAINED IN THE LUNG FUNCTION PREDICTOR, ACCESSED THROUGH THE LUNG FUNCTION PREDICTOR OR PROVIDED BY THE LUNG FUNCTION PREDICTOR IS FOR INFORMATIONAL PURPOSES ONLY AND IN NO WAY IS INTENDED TO SERVE AS A SUBSTITUTE FOR PROFESSIONAL MEDICAL ADVICE OR INTENDED TO PROVIDE ANY MEDICAL OR CLINICAL JUDGMENT OR INDIVIDUALIZED PATIENT CARE. THE END USER SHOULD SEEK PROFESSIONAL MEDICAL ADVICE IN EVALUATING THE INFORMATION PROVIDED WITHIN THE LUNG FUNCTION PREDICTOR.  UBC ALSO RECOMMENDS THAT THE END USER CONSULT WITH MEDICAL PROFESSIONALS FOR HEALTH EVALUATION, DIAGNOSTIC OR TREATMENT DECISIONS. 

DISCLAIMER OF WARRANTY – The End User acknowledges and agrees that the LUNG FUNCTION PREDICTOR is being provided “as is” and that to the extent that the LUNG FUNCTION PREDICTOR or any such updates, upgrades or enhancements to the LUNG FUNCTION PREDICTOR are provided by or on behalf of UBC to the End User, the following disclaimers of warranty and limitations of liability shall apply in connection therewith. UBC does not: (a) warrant or guarantee that any content or other information contained in the LUNG FUNCTION PREDICTOR or accessed through the LUNG FUNCTION PREDICTOR or provided by the LUNG FUNCTION PREDICTOR is accurate or error free; (b) undertake to provide the End User with any maintenance or support services related to the LUNG FUNCTION PREDICTOR, including, without limitation, any updates, upgrades or enhancements thereto; or (c) assume any obligation to obtain and update any content or information in the LUNG FUNCTION PREDICTOR or accessed through LUNG FUNCTION PREDICTOR or provided by the LUNG FUNCTION PREDICTOR

The End User further acknowledges and agrees that: (i) the LUNG FUNCTION PREDICTOR is intended for use only as a research and educational tool;  (ii) it is the sole responsibility of the End User to determine his/her application and use of the LUNG FUNCTION PREDICTOR, (iii) the LUNG FUNCTION PREDICTOR is not intended as a replacement for professional medical advice or a health professional’s medical and clinical judgment (iv) UBC will not be responsible for any errors, misstatements, inaccuracies or omissions regarding the LUNG FUNCTION PREDICTOR or any delays in or interruptions in use of the LUNG FUNCTION PREDICTOR, (v) UBC has no control of or responsibility for the End User's use of the LUNG FUNCTION PREDICTOR and has no knowledge of the specific or unique circumstances under which the LUNG FUNCTION PREDICTOR or information provided by the LUNG FUNCTION PREDICTOR may be used by the End User; and (vi) the End User assumes sole responsibility for any and all use of the LUNG FUNCTION PREDICTOR including any use of any content or other information contained LUNG FUNCTION PREDICTOR, accessed through the LUNG FUNCTION PREDICTOR or provided by the LUNG FUNCTION PREDICTOR.  Furthermore, the End User acknowledges that the LUNG FUNCTION PREDICTOR is being provided WITHOUT REPRESENTATION OR WARRANTY OF ANY KIND.  BY WAY OF EXAMPLE AND NOT LIMITATION, UBC MAKES NO REPRESENTATIONS OR WARRANTIES OF COMMERCIAL UTILITY, TITLE, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OR ANY OTHER WARRANTY, EXPRESS OR IMPLIED.  UBC MAKES NO REPRESENTATION THAT THE USE OF THE LUNG FUNCTION PREDICTOR WILL NOT INFRINGE ANY PATENT, COPYRIGHT, TRADEMARK OR OTHER PROPERTY OR PROPRIETARY RIGHTS.  

LIMITATION OF LIABILITY -  UBC will not be liable to the End User or any other person or entity (including but not limited to persons treated by the End User or on behalf of the End User) for any liability, loss or damages caused or alleged to have been caused, either directly or indirectly, by the use of LUNG FUNCTION PREDICTOR.  Without limitation, in no event will UBC be liable for any tort, personal injury, medical malpractice, misdiagnosis, death, product liability, loss of profit or data, or for special, indirect, consequential, incidental or punitive damages, however caused and regardless of the theory of liability, arising out of or related to the use of or inability to use the LUNG FUNCTION PREDICTOR, even if UBC has been advised of the possibility of such loss or damages. 

INDEMNITY - TO THE FULLEST EXTENT PERMITTED BY LAW, THE END USER AGREES TO INDEMNIFY, DEFEND AND HOLD HARMLESS UBC AND ITS BOARD OF GOVERNORS, OFFICERS, DIRECTORS, FACULTY, STUDENTS, EMPLOYEES AND AGENTS (COLLECTIVELY THE "INDEMNITEES") FROM AND AGAINST ALL CLAIMS, ACTIONS LIABILITIES, LOSSES, EXPENSES, DAMAGES AND COSTS (INCLUDING, WITHOUT LIMITATION, REASONABLE LEGAL FEES) ("CLAIMS") THAT MAY AT ANY TIME BE INCURRED BY ANY OF THEM BY REASON OF ANY CLAIMS, SUITS OR PROCEEDINGS ARISING FROM (A) THE END USER’S USE OF THE LUNG FUNCTION PREDICTOR OR BY ANY OTHER PARTY AUTHORIZED BY THE END USER, AND (B) ANY BREACH BY END USER OF ANY REPRESENTATION, CONDITION OR TERM OF THIS LICENSE AGREEMENT.  WITHOUT LIMITATION, THIS INDEMNITY SHALL INCLUDE ANY CLAIMS BROUGHT BY THIRD PARTIES AGAINST THE INDEMNITEES IN TORT, OR FOR PERSONAL INJURY, MEDICAL MALPRACTICE, MISDIAGNOSIS, DEATH, PRODUCT LIABILITY, LOSS OF PROFIT OR DATA, OR FOR SPECIAL, INDIRECT, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, ARISING OUT OF OR RELATED TO THE END USER'S USE OF, OR INABILITY TO USE, LUNG FUNCTION PREDICTOR
GOVERNING LAW – This Agreement will be governed and interpreted according to the laws of British Columbia, Canada.  The Licensee agrees that by accepting the terms of this Agreement and using the LUNG FUNCTION PREDICTOR, the Licensee has attorned to the exclusive jurisdiction of the courts of competent authority in the Province of British Columbia.

